"""Inject build timestamp into src/build_info.h before each compile."""
import os
from datetime import datetime

Import("env")

INFO = os.path.join(env["PROJECT_DIR"], "src", "build_info.h")
TS = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

contents = (
    "// Auto-generated by scripts/pre_build.py - do not edit by hand.\n"
    "#pragma once\n\n"
    '#define ON3PORK_VERSION "0.4.1"\n'
    '#define ON3PORK_NAME    "0n3Pork W3b"\n'
    '#define ON3PORK_BUILD   "{ts}"\n'.format(ts=TS)
)
with open(INFO, "w", encoding="utf-8") as f:
    f.write(contents)

print("[pre_build] wrote {p} (build={t})".format(p=INFO, t=TS))